[package]
name = "limine-rust-barebones"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.1"
spin = "0.9"

[profile.dev]
opt-level = 3

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

